# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E34fGOEnEmDPmOkazpUKhpqwpwXZv-r
"""

!pip install python-telegram-bot

import telegram.ext
from telegram.ext import Application, CommandHandler, MessageHandler, filters
import telegram
import logging

def start(update, context):
    update.message.reply_text("Hello! Welcome to Simplilearn")

def help_command(update,context):
    update.message.reply_text("""
    The following commands are avilable:

    /start -> Welcome to the channel
    /help -> This message
    /content -> Simplilearn offers various courses free of course through Skillup by Simplilearn
    /Python  -> The first video from Python Playlist
    /SQL -> The first video from SQL Playlist
    /Java -> The first video from Java Playlist
    /Skillup -> Free platform for certification by Simplilearn
    /contact -> contact information
     """)

def content(update, context):
    update.message.reply_text("We have various playlists and articles available!")

def Python(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/Tm5u97I7OrM")

def SQL(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/pFq1pgli0OQ")

def Java(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/i6AZdFxTK9I")

def Skillup(update, context):
    update.message.reply_text("tutorial link : https://www.simplilearn.com/?&utm_source=google&utm_medium=cpc&utm_term=%2Bwww%20%2Bsimplilearn%20%2Bcom&utm_content=803350713-40537012023-467574577661&utm_device=c&utm_campaign=Search-Brand-Broad-IN-AllDevice-adgroup-brand-navigation&gclid=Cj0KCQjw0oyYBhDGARIsAMZEuMv5mA9EysZZ5NfhK65Cb5OU0Q0TVC4con6DQzHF502-dfgA7QQFCgQaAu5sEALw_wcB")

def contact(update, context):
    update.message.reply_text("You can contact on the official mail id")

def handle_message(update, context):
    update.message.reply_text(f"You said {update.message.text}, use the commands using /")


Token = ("Paste your Telegram bot token here")

application = Application.builder().token(Token).build()

application.add_handler(CommandHandler('start',start))
application.add_handler(CommandHandler('help',help_command))
application.add_handler(CommandHandler('content',content))
application.add_handler(CommandHandler('Python',Python))
application.add_handler(CommandHandler('SQL',SQL))
application.add_handler(CommandHandler('Java',Java))
application.add_handler(CommandHandler('Skillup',Skillup))
application.add_handler(CommandHandler('contact',contact))
application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

application.run_polling()



from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

# Create a new chatbot instance
chatbot = ChatBot(
    'ChatBot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    database_uri='sqlite:///database.sqlite3'
)

# Create a new trainer for the chatbot
trainer = ChatterBotCorpusTrainer(chatbot)

# Train the chatbot based on the English corpus
trainer.train('chatterbot.corpus.english')

print("Type 'exit' to end the chat.")

# Chat with the chatbot
while True:
    try:
        user_input = input("You: ")

        if user_input.lower() == 'exit':
            print("ChatBot: Goodbye!")
            break

        # Get a response to the input from the chatbot
        response = chatbot.get_response(user_input)
        print(f"ChatBot: {response}")

    except (KeyboardInterrupt, EOFError, SystemExit):
        break

import telegram.ext

def start(update, context):
    update.message.reply_text("Hello! Welcome to Simplilearn")

def help(update,context):
    update.message.reply_text("""
    The following commands are avilable:

    /start -> Welcome to the channel
    /help -> This message
    /content -> Simplilearn offers various courses free of course through Skillup by Simplilearn
    /Python  -> The first video from Python Playlist
    /SQL -> The first video from SQL Playlist
    /Java -> The first video from Java Playlist
    /Skillup -> Free platform for certification by Simplilearn
    /contact -> contact information
     """)

def content(update, context):
    update.message.reply_text("We have various playlists and articles available!")

def Python(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/Tm5u97I7OrM")

def SQL(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/pFq1pgli0OQ")

def Java(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/i6AZdFxTK9I")

def Skillup(update, context):
    update.message.reply_text("tutorial link : https://www.simplilearn.com/?&utm_source=google&utm_medium=cpc&utm_term=%2Bwww%20%2Bsimplilearn%20%2Bcom&utm_content=803350713-40537012023-467574577661&utm_device=c&utm_campaign=Search-Brand-Broad-IN-AllDevice-adgroup-brand-navigation&gclid=Cj0KCQjw0oyYBhDGARIsAMZEuMv5mA9EysZZ5NfhK65Cb5OU0Q0TVC4con6DQzHF502-dfgA7QQFCgQaAu5sEALw_wcB")

def contact(update, context):
    update.message.reply_text("You can contact on the official mail id")

def handle_message(update, context):
    update.message.reply_text(f"You said {update.message.text}, use the commands using /")


Token = ("7676572166:AAEhimgJ3Tz7yr0KOoVwnwdEaIK0l00jqCk")
#print(bot.get_me())
updater = telegram.ext.Updater("7676572166:AAEhimgJ3Tz7yr0KOoVwnwdEaIK0l00jqCk", telegram.ext.Defaults==True)
disp = updater.dispatcher

disp.add_handler(telegram.ext.CommandHandler('start',start))
disp.add_handler(telegram.ext.CommandHandler('help',help))
disp.add_handler(telegram.ext.CommandHandler('content',content))
disp.add_handler(telegram.ext.CommandHandler('Python',Python))
disp.add_handler(telegram.ext.CommandHandler('SQL',SQL))
disp.add_handler(telegram.ext.CommandHandler('Java',Java))
disp.add_handler(telegram.ext.CommandHandler('Skillup',Skillup))
disp.add_handler(telegram.ext.CommandHandler('contact',contact))
disp.add_handler(telegram.ext.MessageHandler(telegram.ext.Filters.text, handle_message))
updater.start_polling()
updater.idle()



import telegram.ext

def start(update, context):
    update.message.reply_text("Hello! Welcome to Simplilearn")

def help(update,context):
    update.message.reply_text("""
    The following commands are avilable:

    /start -> Welcome to the channel
    /help -> This message
    /content -> Simplilearn offers various courses free of course through Skillup by Simplilearn
    /Python  -> The first video from Python Playlist
    /SQL -> The first video from SQL Playlist
    /Java -> The first video from Java Playlist
    /Skillup -> Free platform for certification by Simplilearn
    /contact -> contact information
     """)

def content(update, context):
    update.message.reply_text("We have various playlists and articles available!")

def Python(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/Tm5u97I7OrM")

def SQL(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/pFq1pgli0OQ")

def Java(update, context):
    update.message.reply_text("tutorial link : https://youtu.be/i6AZdFxTK9I")

def Skillup(update, context):
    update.message.reply_text("tutorial link : https://www.simplilearn.com/?&utm_source=google&utm_medium=cpc&utm_term=%2Bwww%20%2Bsimplilearn%20%2Bcom&utm_content=803350713-40537012023-467574577661&utm_device=c&utm_campaign=Search-Brand-Broad-IN-AllDevice-adgroup-brand-navigation&gclid=Cj0KCQjw0oyYBhDGARIsAMZEuMv5mA9EysZZ5NfhK65Cb5OU0Q0TVC4con6DQzHF502-dfgA7QQFCgQaAu5sEALw_wcB")

def contact(update, context):
    update.message.reply_text("You can contact on the official mail id")

def handle_message(update, context):
    update.message.reply_text(f"You said {update.message.text}, use the commands using /")


Token = ("7676572166:AAEhimgJ3Tz7yr0KOoVwnwdEaIK0l00jqCk")
#print(bot.get_me())
# Removing 'use_context=True' as it is no longer required
updater = telegram.ext.Updater("7676572166:AAEhimgJ3Tz7yr0KOoVwnwdEaIK0l00jqCk")
disp = updater.dispatcher

disp.add_handler(telegram.ext.CommandHandler('start',start))
disp.add_handler(telegram.ext.CommandHandler('help',help))
disp.add_handler(telegram.ext.CommandHandler('content',content))
disp.add_handler(telegram.ext.CommandHandler('Python',Python))
disp.add_handler(telegram.ext.CommandHandler('SQL',SQL))
disp.add_handler(telegram.ext.CommandHandler('Java',Java))
disp.add_handler(telegram.ext.CommandHandler('Skillup',Skillup))
disp.add_handler(telegram.ext.CommandHandler('contact',contact))
disp.add_handler(telegram.ext.MessageHandler(telegram.ext.Filters.text, handle_message))
updater.start_polling()
updater.idle()

!pip install python-telegram-bot